### ISSUE TITLE
Feature Proposal: Interrupt Code Cell

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#20]
**Problem Statement**: Sometimes the code being executed can take abnormally long to run, c.f. `webr::install()` in situations where the COEP & COOP headers have not been set. Alternatively, we have an endless loop that goes on and on.. 

**Proposed change**: 
Add an interrupt button next to the run code button:
<img width="709" alt="webr-stop-code-cell" src="https://github.com/coatless/quarto-webr/assets/833642/6dc47bf8-e125-446f-97ec-e49da1905c83">

As part of the initialization, we should need:

```js
  // Switch stop buttons to being active
  document.querySelectorAll(".btn-webr-stop").forEach((btn) => {
    btn.innerText = "🛑 Stop";
    btn.disabled = false;
  });
```

For each code cell, we would need: 

```
<button class="btn btn-default btn-webr-stop" disabled type="button" id="webr-stop-button-{{WEBRCOUNTER}}">Loading
    webR...</button>
```

```js
  const stopButton = document.getElementById("webr-stop-button-{{WEBRCOUNTER}}");
```

```js
  // Add a click event listener to the stop button
  // terminates the active code run
  stopButton.onclick = async function () {
     await globalThis.webR.interrupt();
  };
```

**Issues**:
Directly trying to issue an interrupt call to `webR` via `globalThis.webR.interrupt();` triggers uncaught promises inside of the `UnwindProtectException`. 

We may want to instead think of the webR session through a [`Console` ](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.Console.html) in `webR` instead of a pure [`webR` object](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html). More research is needed.

<details>
<summary>Interrupt webR hiccups</summary>

```js
(index):1081 Uncaught (in promise) UnwindProtectException: A non-local transfer of control occured during evaluation
    at eval (eval at addEmAsm (https://webr.r-wasm.org/v0.1.1/R.bin.js:2:222381), <anonymous>:1:20)
    at runEmAsmFunction (https://webr.r-wasm.org/v0.1.1/R.bin.js:2:357436)
    at _emscripten_asm_const_int (https://webr.r-wasm.org/v0.1.1/R.bin.js:2:357587)
    at safe_eval_cleanup (wasm://wasm/49cf2636:wasm-function[46]:0x15a7)
    at invoke_vii (https://webr.r-wasm.org/v0.1.1/R.bin.js:2:898483)
    at https://webr.r-wasm.org/v0.1.1/R.bin.wasm:wasm-function[14651]:0x7c3738
    at ffi_safe_eval (wasm://wasm/49cf2636:wasm-function[45]:0x14d3)
    at safeEval (https://webr.r-wasm.org/v0.1.1/webr-worker.js:1448:86)
    at captureR (https://webr.r-wasm.org/v0.1.1/webr-worker.js:2841:32)
    at ServiceWorkerChannelWorker.dispatch (https://webr.r-wasm.org/v0.1.1/webr-worker.js:2503:31)
```

</details>

Sample implementation in: 

https://github.com/coatless/quarto-webr/tree/interrupt-code-cell

**Comment by coatless** [comment]
As the interrupt code only worked with COEP and COOP headers being set for the `shared-array-buffer` option, we're going to close out this option. The vast majority of use cases are either through `post-message` or `service-worker`.
